// Configuration constants
export const CONFIG = {
    CARD_SELECTORS: [
        '.manga-cards__item',
        '.card-filter-list__card',
        '.deck__item',
        '.deck__list .deck__item',
        '.trade__main-item',
        '.trade__main-items a',
        '.trade__main-items--creator a',
        '.trade__main-items--receiver a',
        '.exchange-card',
        '.exchange__card',
        '.exchange-item__card',
        '.trade-card',
        '.trade__card',
        '[data-exchange-card]',
        '.pack-card',
        '.pack__card',
        '.pack-opening__card',
        '.lootbox__card',
        '.gacha-card',
        '.gacha__result-card',
        '[data-pack-card]',
        '.modal-card',
        '.popup-card'
    ],
    BATCH_SIZE: 4,
    PAUSE_BETWEEN_REQUESTS: 4200,
    REQUEST_TIMEOUT: 10000,
    MAX_RETRIES: 3,
    RETRY_429_DELAY: 15000,
    RETRY_429_MAX_ATTEMPTS: 3,
    OWNERS_PER_PAGE: 36,
    WANTS_PER_PAGE: 60,
    CACHE_KEY: 'mbuf_cache_v3',
    ENABLED_KEY: 'mbuf_enabled',
    MAX_REQUESTS_PER_MINUTE: 70,
    RATE_LIMIT_WINDOW: 60000,
    OWNERS_APPROXIMATE_THRESHOLD: 11,
    WANTS_APPROXIMATE_THRESHOLD: 5,
    OWNERS_LAST_PAGE_ESTIMATE: 18,
    WANTS_LAST_PAGE_ESTIMATE: 30,
    DEBUG: false
};
